### ISSUE TITLE
Github CI fails

### ISSUE THREAD

**Issue by tilmanb** [lat-lon/sep3-tools#17]
The github CI project fails with
> Error:  Failed to execute goal on project sep3-parser: Could not resolve dependencies for project org.sep3.tools:sep3-parser:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.postgresql:pljava-api:jar:1.6.3: Failed to read artifact descriptor for org.postgresql:pljava-api:jar:1.6.3: Could not transfer artifact org.postgresql:pljava-api:pom:1.6.3 from/to latlon (https://repo.lat-lon.de/repository/maven-public/): authentication failed for https://repo.lat-lon.de/repository/maven-public/org/postgresql/pljava-api/1.6.3/pljava-api-1.6.3.pom, status: 401 Unauthorized -> [Help 1]

See https://github.com/lat-lon/sep3-tools/runs/5006848135?check_suite_focus=true

**Comment by tfr42** [comment]
Added local repo on github https://github.com/lat-lon/sep3-tools/tree/repository containing artifact build from https://github.com/tada/pljava/

**Comment by tfr42** [comment]
Build action updated to use temurin jdk 16. Now the github action completed successfully, https://github.com/lat-lon/sep3-tools/actions.
